[server]
port = 8501


[theme]
primaryColor = "#1b4d57"  # Primary color used in the app
backgroundColor = "#F0F0F5"  # Background color for the app
secondaryBackgroundColor = "#E0E0EF"  # Secondary background color
textColor = "#1b4d57"  # Color of the text in the app