# [server]
# port = 8501
[ui]
hideSidebarNav = true
hideTopBar = true

[theme]
primaryColor = "#475b7c"               # Primary color used in the app, buttons, dates, text etc
backgroundColor = "#ffffff"            # Background color for the app
secondaryBackgroundColor = "#F2F2F2"   # Secondary background color, sidebar menu
textColor = "dark-gray"                  # Color of the text in the app
font = "sans serif"                    # Font used in the app

[widgets]
backgroundColor = "#f6f7f8"            # Background color for the widgets
secondaryBackgroundColor = "#3F7373"    # Secondary background color for the widgets
textColor = "#1b4d57"                  # Color of the text in the widgets
font = "sans serif"                    # Font used in the widgets








